version: "3.8"

services:
  nginx:
    image: "nginx:1.23.1-alpine"
    networks:
      - streaming-network
    ports:
      - "80:80"
      # Uncomment the line below in case of use SSL
      #- "443:443"
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # Uncomment the line below in case of use SSL
      #- ./config/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - icecast
  icecast:
    build: "."
    image: "icecast:2.4.4"
    networks:
      - streaming-network
    volumes:
      - ./config/icecast/icecast.xml:/etc/icecast.xml
    restart: always

networks:
  streaming-network:
    name: streaming-network
    driver: bridge
    attachable: false
